//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBuses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_ProyectoBusesEntities1 : DbContext
    {
        public bd_ProyectoBusesEntities1()
            : base("name=bd_ProyectoBusesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<destino> destino { get; set; }
        public virtual DbSet<pasaje> pasaje { get; set; }
    }
}
