//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBuses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasaje
    {
        public int id_pasaje { get; set; }
        public int id_bus { get; set; }
        public string rut_cliente { get; set; }
        public int precio { get; set; }
        public string fecha { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
